### ISSUE TITLE
javascript:alert('😼')

### ISSUE THREAD

**Issue by bermanboris** [nelsontky/gh-pages-url-shortener#10]
XSS on https://nlsn.cf/18

**Comment by ermik** [comment]
lol

**Comment by nelsontky** [comment]
Great spot never knew the `javascript:` protocol was a thing LOL. Thanks for the issue it's fixed in d1e4ae9c7db65de58a50c00fe0fba744111728a4

**Comment by ermik** [comment]
d1e4ae9 implements is a blacklist-based system, which is insecure. Read more from the fabulous folk at @phacility (I think @epriestley wrote flavor text): [https://secure.phabricator.com/book/phabflavor/article/things_you_should_do_now/#never-design-a-blacklist-based](https://secure.phabricator.com/book/phabflavor/article/things_you_should_do_now/#never-design-a-blacklist-based)

**Comment by nelsontky** [comment]
Thank you I did learn a lot!
