### ISSUE TITLE
You can write a bot to create PRs from the issues and update a json file in the repo

### ISSUE THREAD

**Issue by atakanyenel** [nelsontky/gh-pages-url-shortener#48]
Currently you are sending a request to Github API to read repos and do the redirecting. I assume you don't do caching, (maybe github does), so you add latency to every request and consume your github api rate limit. 

Instead, you can write a github bot that takes issues in the other repo and opens a PR to this repo where it submits redirections to a json file. This workflow is automated as well and will fixes all the problems above. The only problem is the delay between adding the issue and it being submitted to repo and the initial bot development time.

* I know this project is experimenting only and there is no need for what I explained above, It's actually very smart the way it is,  but just wanted to put it here.

**Comment by nelsontky** [comment]
Ah actually quite a few people have suggested this. I am not really into doing this cause there will be about a one minute lag in the adding of short links. Someone suggested on HN to use a `<meta>` refresh header, and this can be accomplished by generating a HTML file for each issue added to the "database". 

Aside from the lag, using a bot or any form of github actions would make the setup way more complicated than what it is currently, and one of the goals here is to make it easily to create forks for others to host.

That being said, thank you for your comments, you could look at the [HN post](https://news.ycombinator.com/item?id=25110879) for some of the other suggestions and if you do implement them, you could add your fork to the README by opening a PR. Thank you!
