### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by Pajsen9263** [nelsontky/gh-pages-url-shortener#5]
How did you use a package.json, github.io dosen't have support for that right?

**Comment by nelsontky** [comment]
It does not have support for that yes. I only use it for development, and I have a script that does deployment for me

**Comment by kidGodzilla** [comment]
1. CNAME points URL to `gh-pages` branch
2. 404.html handles all requests
3. Small javascript snippet fetches a JSON representation of the GitHub issue via the JSON API, and redirects to the issue title, as a URL.
4. Profit?

**Comment by nelsontky** [comment]
Thank you for the explanation maybe I'll add it to the README
