### ISSUE TITLE
Thought exercise: Make a dating site

### ISSUE THREAD

**Issue by impredicative** [nelsontky/gh-pages-url-shortener#52]
Per your experience, is it feasible to make a simple serverless dating site+app which uses Issues for hosting? It could encode each user's profile as an issue, and the pictures as encoded comments to the issue. Categories and classifications can be made using Labels. Age and height search can perhaps be implemented using Milestones or any other means of range matching, although I'm not sure. Sent and received messages can be hosted as comments to the issue as well. I'm sure there will be more ideas as it's implemented.

This is a bit trickier because users of the site would expect to be able to remove or edit their profile, without anyone else except the admin being able to do the same. The same user-level security restriction also applies for reading and deleting one's messages.

Up to ten new prospective matches can be given to each active user daily using a matching job which runs nightly using Actions.

**Comment by nelsontky** [comment]
I would believe some of what you said is possible. There is currently a 60 request per hour limit for the issues API, but if we were to login to our GitHub accounts (which would make sense given its a geeky dating site), that rises to 5000 per hour, so I don't think rate limits will be an issue when browsing profiles. That being said, messages as comments would not be that great of an idea as it would need some form of re-polling of the api every few intervals to make it look real time. This will take a hit on the 5000 calls per hour. That being said, I believe we could do the messaging peer to peer via WebRTC, that does not need a server and we could store chat logs in localstorage (up to 5mb). While all this is very possible, I don't believe that it would be a particularly pleasant experience!
