### ISSUE TITLE
Github Issues API is not available on private repo except you generate the access token.

### ISSUE THREAD

**Issue by khvmaths** [nelsontky/gh-pages-url-shortener#61]
Just a suggestion to add in the Readme to highlight if they want the repo to be private.

Generate Personal Access Token with full repo control at `Settings/Developer Settings/Personal Access Token`. 

Add the generated token to `404.html` page at line 70, where 
`xhr.open("GET", GITHUB_ISSUES_LINK + issueNumber + "?access_token=<YOUR_TOKEN_HERE>");`

_EDIT: Quick Note: this method will no longer work starting May 5, 2021 at 16:00 UTC. Instead use the authorization header stated below._

Once again, thank you for this awesome repo!

**Comment by nelsontky** [comment]
Hmm that's a great suggestion! Quick question since I'm not very familiar with the GitHub API. Is there a way to limit the functionalities of a generated token to ensure security of this method?

**Comment by khvmaths** [comment]
You can limit the token's scope, as stated [here](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token).

Sadly, this direct call method support will be ended by next year as stated [here](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/). Instead, add the header to XML call, with `xhr.setRequestHeader("Authorization","token <YOUR TOKEN>")`, but I can't seem to get it working.

**Comment by nelsontky** [comment]
Great! I will add it into the README when I have the time! If you do have a fork, feel free to let me know too and I can feature your fork on the README too! Thank you!

**Comment by khvmaths** [comment]
Hi @nelsontky I didn't do any fork. Just a suggestion here 👍
