### ISSUE TITLE
A command line tool for this idea

### ISSUE THREAD

**Issue by Mayandev** [nelsontky/gh-pages-url-shortener#63]
Thx for the idea.
I publish a command line tool , now we can convert short url in terminal.

- [GitHub](https://github.com/Mayandev/gh-short-url)
- [NPM](https://www.npmjs.com/package/gh-short-url)

![image](https://user-images.githubusercontent.com/28648715/102714280-719f5980-4308-11eb-9996-7e39e91ce712.png)

**Comment by nelsontky** [comment]
Added to README!
