### ISSUE TITLE
能不能设置域名自动跳转到二级目录/1?

### ISSUE THREAD

**Issue by Posuomen** [nelsontky/gh-pages-url-shortener#65]

**Comment by nelsontky** [comment]
If I understood your question correctly (chinese is my second language), yes it is possible. According to the [README](https://github.com/nelsontky/gh-pages-url-shortener/blob/main/README.md):

> 1. Change `var PATH_SEGMENTS_TO_SKIP = 0;` at the top of `404.html` to `var PATH_SEGMENTS_TO_SKIP = 1;`.

You can change that variable to match any number of path segments in your base url. Let me know if I misunderstood your question.

**Comment by nelsontky** [comment]
Closed due to inactivity

**Comment by Posuomen** [comment]
well,i want to use the main domain to jump,but it can only use second level directory to jump.
