### ISSUE TITLE
Custom Domains / Existing Website

### ISSUE THREAD

**Issue by 42piratas** [nelsontky/gh-pages-url-shortener#88]
Hi there! Great project! 

I have two questions:

1 - Is there a way to create custom URLs? E.g. domain.com/customurl, domain.com/heythere
2 - Would I be able to use the tool in tandem with an existing website, i.e. domain.com has a static landing page and some sub-pages, which will continue to be accessible, plus the extra domains created by the tool? 

Cheers!

**Comment by nelsontky** [comment]
Hey good morning friends thanks for the questions! There is no way to create custom urls (unless we have a mechanism that uses issues titles as the alias), while it is possible to make it work with a domain with a static landing page, it might take more work and depends on the tech stack of the landing page involved
